from pathlib import Path

PS1=Path("windows/NEXUS_AUTH_RETRY_CURRENT.ps1")
CMD=Path("windows/NEXUS_AUTH_RETRY_CURRENT.cmd")
POLICY=Path(".project-memory/DELIVERY_REDUNDANCY_POLICY.json")
SERVER=Path("windows/bcp_server.py")
REGISTRY=Path(".project-memory/UNIVERSAL_CONTINUATION_CODE_REGISTRY.json")
CONTINUITY=Path("API_PROJECT_CONTINUITY.md")

def ck(name, cond):
    print(("PASS" if cond else "FAIL"), name)
    if not cond:
        raise AssertionError(name)

def main():
    p=PS1.read_text(encoding="utf-8")
    c=CMD.read_text(encoding="utf-8")
    policy=POLICY.read_text(encoding="utf-8")
    server=SERVER.read_text(encoding="utf-8")
    registry=REGISTRY.read_text(encoding="utf-8")
    continuity=CONTINUITY.read_text(encoding="utf-8")
    ck("local-endpoint-only", 'http://127.0.0.1:8765/v1/system/nexus/retry-auth' in p)
    ck("no-cloudflare-direct-url", "cloudflare.com" not in p.lower())
    ck("no-classic-localhost-oauth", "8976" not in p)
    ck("local-token-read", 'bcp_token.txt' in p)
    ck("token-not-printed", 'Write-Host $token' not in p and 'echo %TOKEN%' not in c)
    ck("explicit-confirm", 'confirm = $true' in p)
    ck("server-imports-uuid", "import uuid" in server)
    ck("server-retry-uses-uuid", "explicit_retry_nonce\": uuid.uuid4().hex" in server)
    ck("bounded-timeout", '-TimeoutSec 12' in p)
    ck("single-rest-call", p.count("Invoke-RestMethod")==1)
    ck("launched-pass", 'NEXUS_FRESH_DEVICE_FLOW_STARTED' in p)
    ck("unexpected-hold", 'HOLD NEXUS_UNEXPECTED_RESULT' in p)
    ck("cmd-one-shot", 'NEXUS_AUTH_RETRY_CURRENT.ps1' in c and 'pause' in c.lower())
    ck("mail-primary-detailed", '"role": "SOLE_PRIMARY_DETAILED_HUMAN_CHECKPOINT_DELIVERY"' in policy)
    ck("chat-pointer-only", '"role": "POINTER_ONLY_AFTER_SUCCESSFUL_EMAIL_END_ACK"' in policy)
    ck("start-mail-before-work", '"start_notice_required_before_substantive_work": true' in policy)
    ck("end-mail-before-chat", '"end_checkpoint_required": true' in policy)
    ck("end-mail-provider-ack", '"end_mail_provider_ack_required": true' in policy)
    ck("end-mail-retry", '"end_mail_retry_required": true' in policy)
    ck("chat-before-end-ack-forbidden", '"chat_output_before_end_ack_forbidden": true' in policy)
    ck("end-watchdog-at-start", '"end_watchdog_required_at_start": true' in policy)
    ck("end-watchdog-25-min", '"end_watchdog_offset_minutes": 25' in policy)
    ck("chat-no-full-body", '"detailed_checkpoint_body_forbidden_after_successful_email": true' in policy)
    ck("mail-before-chat-pointer", '"send_before_chat_pointer": true' in policy)
    ck("continuation-loads-delivery-policy", "DELIVERY_REDUNDANCY_POLICY.json" in registry and "DELIVERY_REDUNDANCY_POLICY.json" in continuity)
    ck("pre-human-simulation-policy", "PRE_HUMAN_ACTION_SIMULATION_POLICY.json" in registry and "Pre-human action simulation invariant" in continuity)
    ck("continuation-start-end-email", '"email_start_notice_before_substantive_work": true' in registry and '"email_end_checkpoint_before_chat_pointer": true' in registry and "START/END Gmail handshake" in continuity)
    ck("continuation-25-minute-cadence", '"cadence_target_minutes": 25' in registry and "targeting 25 minutes" in continuity)
    ck("checkpoint-subject-policy", 'subject_must_include_checkpoint_id' in policy)
    ck("nested-zip-forbidden", 'nested_zip_for_user_action_forbidden' in policy)
    print("R55_DELIVERY_POLICY_AND_NEXUS_HELPER=PASS")
    return 0

if __name__=="__main__":
    raise SystemExit(main())
