from pathlib import Path

PS1=Path("windows/NEXUS_AUTH_RETRY_CURRENT.ps1")
CMD=Path("windows/NEXUS_AUTH_RETRY_CURRENT.cmd")
POLICY=Path(".project-memory/DELIVERY_REDUNDANCY_POLICY.json")
SERVER=Path("windows/bcp_server.py")
REGISTRY=Path(".project-memory/UNIVERSAL_CONTINUATION_CODE_REGISTRY.json")
CONTINUITY=Path("API_PROJECT_CONTINUITY.md")
COMMUNICATION=Path(".project-memory/COMMUNICATION_SURVIVAL_POLICY.json")
COMM_PROTOCOL=Path(".project-memory/COMMUNICATION_PROTOCOL.json")
COMM_STATE_MACHINE=Path(".project-memory/COMMUNICATION_STATE_MACHINE.json")
TAKEOVER=Path(".project-memory/NEW_CONVERSATION_TAKEOVER.json")

def ck(name, cond):
    print(("PASS" if cond else "FAIL"), name)
    if not cond:
        raise AssertionError(name)

def main():
    p=PS1.read_text(encoding="utf-8")
    c=CMD.read_text(encoding="utf-8")
    policy=POLICY.read_text(encoding="utf-8")
    server=SERVER.read_text(encoding="utf-8")
    registry=REGISTRY.read_text(encoding="utf-8")
    continuity=CONTINUITY.read_text(encoding="utf-8")
    communication=COMMUNICATION.read_text(encoding="utf-8")
    comm_protocol=COMM_PROTOCOL.read_text(encoding="utf-8")
    comm_state=COMM_STATE_MACHINE.read_text(encoding="utf-8")
    takeover=TAKEOVER.read_text(encoding="utf-8")
    ck("local-endpoint-only", 'http://127.0.0.1:8765/v1/system/nexus/retry-auth' in p)
    ck("no-cloudflare-direct-url", "cloudflare.com" not in p.lower())
    ck("no-classic-localhost-oauth", "8976" not in p)
    ck("local-token-read", 'bcp_token.txt' in p)
    ck("token-not-printed", 'Write-Host $token' not in p and 'echo %TOKEN%' not in c)
    ck("explicit-confirm", 'confirm = $true' in p)
    ck("server-imports-uuid", "import uuid" in server)
    ck("server-retry-uses-uuid", "explicit_retry_nonce\": uuid.uuid4().hex" in server)
    ck("bounded-timeout", '-TimeoutSec 12' in p)
    ck("single-rest-call", p.count("Invoke-RestMethod")==1)
    ck("launched-pass", 'NEXUS_FRESH_DEVICE_FLOW_STARTED' in p)
    ck("unexpected-hold", 'HOLD NEXUS_UNEXPECTED_RESULT' in p)
    ck("network-recovery-pending", 'NETWORK_RECOVERY_PENDING' in p and 'aucune action requise' in p and 'exit 10' in p)
    ck("cmd-network-wait-not-failure", 'ATTENTE RESEAU - reprise automatique' in c)
    ck("server-preserves-human-gate", 'recovered_human_gate_from_receipt' in server and 'last_stage_check_error_class' in server)
    ck("cmd-one-shot", 'NEXUS_AUTH_RETRY_CURRENT.ps1' in c and 'pause' in c.lower())
    ck("mail-primary-detailed", '"role": "SOLE_PRIMARY_DETAILED_HUMAN_CHECKPOINT_DELIVERY"' in policy)
    ck("chat-pointer-only", '"role": "POINTER_ONLY_AFTER_SUCCESSFUL_EMAIL_END_ACK"' in policy)
    ck("start-mail-before-work", '"start_notice_required_before_substantive_work": true' in policy)
    ck("end-mail-before-chat", '"end_checkpoint_required": true' in policy)
    ck("end-mail-provider-ack", '"end_mail_provider_ack_required": true' in policy)
    ck("end-mail-retry", '"end_mail_retry_required": true' in policy)
    ck("chat-before-end-ack-forbidden", '"chat_output_before_end_ack_forbidden": true' in policy)
    ck("normal-primary-close-no-automation", '"scheduled_close_guards_required": false' in policy and '"normal_owner": "PRIMARY_ASSISTANT"' in policy)
    ck("normal-closeout-23-min", '"normal_closeout_offset_minutes": 23' in policy)
    ck("scheduler-completion-not-delivery", '"scheduler_completion_is_not_delivery_proof": true' in policy and '"scheduler_completed_is_not_delivery": true' in communication)
    ck("foreground-end-primary", '"foreground_end_send_primary": true' in policy)
    ck("chat-no-full-body", '"detailed_checkpoint_body_forbidden_after_successful_email": true' in policy)
    ck("mail-before-chat-pointer", '"send_before_chat_pointer": true' in policy)
    ck("continuation-loads-delivery-policy", "DELIVERY_REDUNDANCY_POLICY.json" in registry and "DELIVERY_REDUNDANCY_POLICY.json" in continuity)
    ck("pre-human-simulation-policy", "PRE_HUMAN_ACTION_SIMULATION_POLICY.json" in registry and "Pre-human action simulation invariant" in continuity)
    ck("continuation-start-end-email", '"email_start_notice_before_substantive_work": true' in registry and '"email_end_checkpoint_before_chat_pointer": true' in registry and "START/END Gmail handshake" in continuity)
    ck("continuation-25-minute-cadence", '"cadence_target_minutes": 25' in registry and '"useful_work_target_minutes": 23' in registry and ("25-minute" in continuity or "25 minutes" in continuity))
    ck("communication-survival-policy", "COMMUNICATION_SURVIVAL_POLICY.json" in registry and "R77 A+B+C Integral Handoff" in continuity)
    ck("communication-no-reexplanation", '"user_reexplanation_required": false' in communication)
    ck("communication-phone-store-forward", '"store_and_forward": true' in communication)
    ck("communication-protocol-ref", '"schema": "bcp.communication_protocol/2"' in comm_protocol and '"normal_close_owner": "PRIMARY_ASSISTANT"' in comm_protocol and '"scheduled_backup_required": false' in comm_protocol)
    ck("communication-state-machine", '"schema": "bcp.communication_state_machine/2"' in comm_state and 'END_SEND_PENDING->END_ACKNOWLEDGED' in comm_state)
    ck("communication-delivery-key", '"delivery_key_required": true' in policy and '"delivery_key_required": true' in registry)
    ck("new-conversation-takeover", '"trigger_code": "BCPGO BCP"' in takeover and "NEW_CONVERSATION_TAKEOVER.json" in registry)
    ck("checkpoint-subject-policy", 'subject_must_include_checkpoint_id' in policy)
    ck("nested-zip-forbidden", 'nested_zip_for_user_action_forbidden' in policy)
    print("R77_25MIN_DELIVERY_STATE_MACHINE_AND_NEXUS_HELPER=PASS")
    return 0

if __name__=="__main__":
    raise SystemExit(main())
